name: PFLB_Poligon_test

on:
  push:
    branches: ["master", "feature/refactorUserInfoTest"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup browser Chrome
        uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
      - name: Run SmokeTest
        env:
          URL: ${{ secrets.URL }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DB_LOGIN: ${{ secrets.DB_LOGIN }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_URL: ${{ secrets.DB_URL }}
          URL_API: ${{ secrets.URL_API }}
          HOST_TOKEN: ${{ secrets.HOST_TOKEN }}
        run: mvn clean -DsuiteXmlFile='src/test/resources/SmokeTest.xml' test -Durl=$URL -Dlogin=$LOGIN -Dpassword=$PASSWORD
          -DdbLogin=$DB_LOGIN -DdbPass=$DB_PASS -DdbUrl=$DB_URL -DurlApi=$URL_API -DhostToken=$HOST_TOKEN -Dselenide.timeout=10000
