name: PFLB_Poligon_test

on:
  push:
    branches: ["master", "feature/AllureReportOnGitHubActions"]
  pull_request:
    branches: ["master"]
  schedule:
      - cron: '0 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup browser Chrome
        uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
      - name: Run SmokeTest
        env:
          URL: ${{ secrets.URL }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DB_LOGIN: ${{ secrets.DB_LOGIN }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_URL: ${{ secrets.DB_URL }}
          URL_API: ${{ secrets.URL_API }}
          HOST_TOKEN: ${{ secrets.HOST_TOKEN }}
        run: mvn clean test -Durl=$URL -Dlogin=$LOGIN -Dpassword=$PASSWORD
          -DdbLogin=$DB_LOGIN -DdbPass=$DB_PASS -DdbUrl=$DB_URL -DurlApi=$URL_API -DhostToken=$HOST_TOKEN
          -Dselenide.timeout=10000 -Dselenide.reportsFolder=target/screenshots

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: selenide-screenshots
          path: target/screenshots

      - name: Copy History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build Report
        uses: simple-elf/allure-report-action@v1.10
        if: always()
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
